# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(blank=True, max_length=256)),
                ('body', wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('position_item', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('company_name', wagtail.wagtailcore.blocks.CharBlock()), ('position', wagtail.wagtailcore.blocks.CharBlock()), ('start_at', wagtail.wagtailcore.blocks.DateBlock()), ('leave_at', wagtail.wagtailcore.blocks.DateBlock(required=False)), ('location', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('website', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False))), icon='doc-full', label='Accordion item'), icon='doc-full', template='about/blocks/position_item_block.html')), ('key_skils', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(), template='about/blocks/key_skils_block.html'))))),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
