language: python
python:
  - 3.6

cache:
  pip: true

# Use container-based infrastructure
dist: trusty
sudo: required

services:
  - postgresql
  - docker

addons:
  postgresql: '9.6'

env:
  global:
    - DJANGO_SETTINGS_MODULE=blog.base.settings.prod
    - DATABASE_URL=postgres://postgres@localhost/test_db
    - CFG_SECRET_KEY=iamnotsosecret
    - CFG_ALLOWED_HOSTS=localhost

before_script:
  - psql -c 'create database test_db;' -U postgres

install:
  - pip install -r src/requirements/requirements.txt
  - pip install flake8

script:
  - flake8
  - python src/manage.py check
  - python src/manage.py makemigrations --check
  - python src/manage.py test
