version: '2'

services:
  blog_app:
    extends:
      file: docker-compose.common.yml
      service: blog_app
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/blog.prod.env
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_postgres:postgres
    depends_on:
      - blog_postgres


  # Runs migrations for the app. Production only, at the moment.
  blog_app_update:
    extends:
      file: docker-compose.common.yml
      service: blog_app
    # Restart until postgres can process our requests.
    # Should help on the first run and on restarts
    restart: on-failure:10
    command: "bash scripts/update-script.sh"
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/blog.prod.env
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_postgres:postgres
    depends_on:
      - blog_postgres


  blog_app_frontend:
    extends:
      file: docker-compose.common.yml
      service: blog_app_frontend
    volumes:
      - "blog_app_data:/var/blog"


  # Nginx. Serves static and media files from the application's data container.
  # Note: allows to run only this app. Production only, at the moment.
  blog_nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_app


  blog_postgres:
    extends:
      file: docker-compose.common.yml
      service: blog_postgres
    volumes:
      - "blog_postgres_data:/var/lib/postgresql"


volumes:
  blog_app_data: {}
  blog_postgres_data: {}
