version: '2'

services:
  blog:
    build: .
    links:
      - postgres:postgres
    depends_on:
      - postgres
      - blog_data
    volumes_from:
      - blog_data
    env_file:
      - ./blog.env
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/blog.env

  blog_data:
    image: python:3.5-slim
    volumes:
      - /var/blog
    command: "true"

  nginx:
    build: ./nginx
    links:
      - blog
    volumes_from:
      - blog_data
    depends_on:
      - blog_data
    ports:
      - "80:80"

  postgres:
    image: postgres:9.5
    volumes_from:
      - postgres_data
    depends_on:
      - postgres_data

  postgres_data:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql
    command: "true"