version: '2'

services:
  # The blog application
  blog_app:
    build: .
    restart: always
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/blog.prod.env
      - ./blog.prod.env
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_postgres:postgres
    depends_on:
      - blog_postgres


  # Nginx. Serves static and media files from the application's data container.
  # Note: allows to run only this app. Production only, at the moment.
  blog_nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_app


  # DB container
  blog_postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - "blog_postgres_data:/var/lib/postgresql/data"


volumes:
  blog_app_data: {}
  blog_postgres_data: {}
