blog:
  build: .
  links:
    - postgres:postgres
  volumes_from:
    - blog_data
  env_file: ./blog.env

blog_post_update:
  build: .
  links:
    - postgres:postgres
  volumes_from:
    - blog_data
  env_file: ./blog.env
  command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput"

blog_data:
  image: python:2.7-slim
  volumes:
    - /var/blog
  command: "true"

nginx:
  build: ./nginx
  links:
    - blog
  volumes_from:
    - blog
  ports:
    - "80:80"
#    - "443:443"

postgres:
  image: postgres:9.4
  volumes_from:
    - postgres_data

postgres_data:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql
  command: "true"