version: '2'

services:
  blog_app:
    extends:
      file: docker-compose.common.yml
      service: blog_app
    env_file:
      - blog.dev.env
    volumes:
      - "./src:/app"
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_postgres:postgres
    depends_on:
      - blog_postgres
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"


  blog_app_frontend:
    extends:
      file: docker-compose.common.yml
      service: blog_app_frontend
    env_file:
      - blog.dev.env
    volumes:
      - "./src:/app"
      - "/app/node_modules"
    volumes:
      - "blog_app_data:/var/blog"
    depends_on:
      - blog_app
    command: "npm run watch"


  blog_postgres:
    extends:
      file: docker-compose.common.yml
      service: blog_postgres
    volumes:
      - "blog_postgres_data:/var/lib/postgresql"


volumes:
  blog_app_data: {}
  blog_postgres_data: {}
