version: '2'


volumes:
  blog_app_data: {}
  blog_postgres_data: {}


networks:
  backend: {}


services:
  # The blog application
  blog_app:
    build: .
    restart: always
    networks:
      - backend
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/blog.prod.env
      - ./blog.prod.env
    volumes:
      - "blog_app_data:/var/blog"
    links:
      - blog_postgres:postgres
    depends_on:
      - blog_postgres


  # DB container
  blog_postgres:
    image: postgres:9.5
    restart: always
    networks:
      - backend
    volumes:
      - "blog_postgres_data:/var/lib/postgresql/data"
