version: '2'

services:
  # The blog application
  blog_app:
    build: .
    env_file:
      - ./blog.prod.env


  # Builds front-end for the app
  blog_app_frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend_build
    env_file:
      - ./blog.prod.env

  # Postgres
  blog_postgres:
    image: postgres:9.5
